#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Mon Jul 24 22:17:40 2017
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_NEW, "New", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_OPEN, "Open", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.Append(wx.ID_SAVE, "Save", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, "Exit", "", wx.ITEM_NORMAL)
        self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1)
        self.window_1 = wx.SplitterWindow(self, wx.ID_ANY)
        self.window_1_pane_1 = wx.Panel(self.window_1, wx.ID_ANY)
        self.navigationNotebook = wx.Notebook(self.window_1_pane_1, wx.ID_ANY)
        self.notebook_1_pane_1 = wx.Panel(self.navigationNotebook, wx.ID_ANY)
        self.window_1_pane_2 = wx.Panel(self.window_1, wx.ID_ANY)
        self.window_2 = wx.SplitterWindow(self.window_1_pane_2, wx.ID_ANY)
        self.window_2_pane_1 = wx.Panel(self.window_2, wx.ID_ANY)
        self.documentsNotebook = wx.Notebook(self.window_2_pane_1, wx.ID_ANY)
        self.notebook_2_pane_1 = wx.Panel(self.documentsNotebook, wx.ID_ANY)
        self.window_2_pane_2 = wx.Panel(self.window_2, wx.ID_ANY)
        self.outputsNotebook = wx.Notebook(self.window_2_pane_2, wx.ID_ANY)
        self.notebook_3_pane_1 = wx.Panel(self.outputsNotebook, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.newFile, id=wx.ID_NEW)
        self.Bind(wx.EVT_MENU, self.openFile, id=wx.ID_OPEN)
        self.Bind(wx.EVT_MENU, self.saveFile, id=wx.ID_SAVE)
        self.Bind(wx.EVT_MENU, self.exit, id=wx.ID_EXIT)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("TestEd")
        self.SetSize((800, 600))
        self.frame_1_statusbar.SetStatusWidths([-1])
        
        # statusbar fields
        frame_1_statusbar_fields = ["frame_1_statusbar"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.navigationNotebook.Hide()
        self.outputsNotebook.Hide()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        self.navigationNotebook.AddPage(self.notebook_1_pane_1, "tab1")
        sizer_2.Add(self.navigationNotebook, 1, 0, 0)
        self.window_1_pane_1.SetSizer(sizer_2)
        self.documentsNotebook.AddPage(self.notebook_2_pane_1, "tab1")
        sizer_4.Add(self.documentsNotebook, 1, 0, 0)
        self.window_2_pane_1.SetSizer(sizer_4)
        self.outputsNotebook.AddPage(self.notebook_3_pane_1, "tab1")
        sizer_5.Add(self.outputsNotebook, 1, 0, 0)
        self.window_2_pane_2.SetSizer(sizer_5)
        self.window_2.SplitHorizontally(self.window_2_pane_1, self.window_2_pane_2, 500)
        sizer_3.Add(self.window_2, 1, wx.EXPAND, 0)
        self.window_1_pane_2.SetSizer(sizer_3)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2, 200)
        sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def newFile(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'newFile' not implemented!"
        event.Skip()

    def openFile(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'openFile' not implemented!"
        event.Skip()

    def saveFile(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'saveFile' not implemented!"
        event.Skip()

    def exit(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'exit' not implemented!"
        event.Skip()

# end of class MyFrame
